### ISSUE TITLE
Support embedded devices without PSTN number

### ISSUE THREAD

**Issue by renne** [signalapp/libsignal-service-java#58]
Currently only devices with a PSTN number are supported. Embedded devices like [door stations, webcams, etc.](https://github.com/espressif/esp-adf/issues/17) should be able to communicate with Signal users, too. I suggest to implement UID support for devices without a PSTN number.

**Comment by nrizzio** [comment]
This is a feature request and feature requests are not permitted on the issue tracker. Please read the contributing guidelines and close this issue. There is a thread on the forum about alternative forms of registration.
