### ISSUE TITLE
How can I make the library support custom api

### ISSUE THREAD

**Issue by zyl0501** [signalapp/libsignal-service-java#59]
[https://github.com/signalapp/libsignal-service-java/blob/master/java/src/main/java/org/whispersystems/signalservice/internal/push/PushServiceSocket.java](url) 
This java file has defined some api. I want expand more api with signal protocol.
I found method makeServiceRequest in PushServiceSocket, but the method is private. How can I make the library support custom api.

**Comment by Trolldemorted** [comment]
This is an issue tracker, not a support ticket system or a forum. If you want to ask questions, the [community forum](https://community.signalusers.org/) is most likely the best place to visit.
