### ISSUE TITLE
Previously working version of client breaking due to lack of senders in payload

### ISSUE THREAD

**Issue by matthew-piziak** [signalapp/libsignal-service-java#79]
Signal-CLI ticket here: https://github.com/AsamK/signal-cli/issues/245

I've also opened a ticket against the Signal team last week, but have gotten no response.

See [this comment](https://github.com/AsamK/signal-cli/issues/245#issuecomment-556399041) for the change in payload behavior.

This is a breaking change for clients; I understand that depending on the source of the fault this may or may not be the correct place to report this issue. In either case, due to a lack of communication from other sources I'm reaching further afield to see if anyone knows where this error is coming from, or if anyone has advice on how to get support for these broken messages.

Thanks in advance for any help.

**Comment by moxie0** [comment]
We don't maintain signal-cli, that's a 3rd party project. Looks like it might not support sealed sender.
